CREATE TABLE STUDENT
(
STD_ID INT,
STD_NAME VARCHAR(50),
STDMAIL_ID VARCHAR(50),
COURSE_ID INT
)

CREATE TABLE COURSE
(
COURSE_ID INT,
COURSE_NAME VARCHAR(100),
COURSE_FEE DECIMAL(7,2)
)

SELECT * FROM STUDENT
SELECT * FROM COURSE

INSERT INTO STUDENT VALUES (101,'Srinias R', 'srinitimotam@gamil.com', 10)
INSERT INTO STUDENT VALUES (102,'Yogitha S', 'yogitha@gmail.com', 20)
INSERT INTO STUDENT VALUES (103,'Sushma H A','sushma@gmail.com', 30)
INSERT INTO STUDENT VALUES (104,'Anu','anu@gmail.com',40)
INSERT INTO STUDENT VALUES (105,'Likith','likith@gmail.com',50)

INSERT INTO COURSE VALUES (10,'EXCEL', 5000),
(20,'SQL',10000),
(30,'SAP',15000),
(40,'PYTHON',2000),
(50,'TABLEAU',25000)

----INNER JOIN------

SELECT * FROM STUDENT AS STD
INNER JOIN
COURSE
ON
STD.COURSE_ID=COURSE.COURSE_ID

--------OUTER JOOIN--------




SELECT * FROM STUDENT AS STD
LEFT JOIN  
COURSE
ON
STD.COURSE_ID=COURSE.COURSE_ID

SELECT * FROM STUDENT AS STD
RIGHT JOIN  
COURSE
ON
STD.COURSE_ID=COURSE.COURSE_ID























